services:

  postgres:
    image: postgres:16-alpine
    container_name: dlq-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB:       dlq
      POSTGRES_USER:     dlq
      POSTGRES_PASSWORD: dlq
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dlq"]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: apache/kafka:3.7.0
    container_name: dlq-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  producer:
    build: .
    container_name: dlq-producer
    command: python -m app.producer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP: "kafka:9092"
      API_URL: "https://jsonplaceholder.typicode.com/posts"
      PRODUCE_INTERVAL_SECONDS: "5"

  consumer:
    build: .
    container_name: dlq-consumer
    command: python -m app.consumer
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP: "kafka:9092"
      CONSUMER_GROUP: "dlq-demo-consumer"
      FAILURE_RATE: "0.2"

  dlq-handler:
    build: .
    container_name: dlq-handler
    command: python -m app.dlq_handler
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP: "kafka:9092"
      CONSUMER_GROUP: "dlq-demo-handler"
      DB_DSN: "host=postgres port=5432 dbname=dlq user=dlq password=dlq"

  api:
    build: .
    container_name: dlq-api
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP: "kafka:9092"
      DB_DSN: "host=postgres port=5432 dbname=dlq user=dlq password=dlq"

volumes:
  pgdata:
